"""
Delta Exchange Authentication Module

This module handles authentication and request signing for the Delta Exchange API.
All authenticated requests require HMAC-SHA256 signature generation.
"""

import hashlib
import hmac
import time
from typing import Dict, Optional

from .exceptions import AuthenticationError


class DeltaAuth:
    """
    Handles authentication and signature generation for Delta Exchange API.
    
    The Delta Exchange API uses HMAC-SHA256 signatures for authentication.
    Each authenticated request requires three headers:
    - api-key: Your API key
    - timestamp: Current Unix timestamp (seconds)
    - signature: HMAC-SHA256 signature
    
    The signature is generated by:
    1. Creating a signature string: METHOD + timestamp + path + query_string + body
    2. Computing HMAC-SHA256 with the API secret as the key
    3. Converting to hexadecimal string
    
    Example:
        >>> auth = DeltaAuth(api_key="your_key", api_secret="your_secret")
        >>> headers = auth.generate_headers("GET", "/v2/positions", "product_id=1", "")
        >>> # Use headers in your HTTP request
    """
    
    def __init__(self, api_key: str, api_secret: str):
        """
        Initialize DeltaAuth with API credentials.
        
        Args:
            api_key: Your Delta Exchange API key
            api_secret: Your Delta Exchange API secret
            
        Raises:
            AuthenticationError: If API key or secret is empty
        """
        if not api_key or not api_secret:
            raise AuthenticationError("API key and secret are required")
        
        self.api_key = api_key
        self.api_secret = api_secret
    
    def generate_signature(
        self,
        method: str,
        timestamp: str,
        path: str,
        query_string: str = "",
        body: str = ""
    ) -> str:
        """
        Generate HMAC-SHA256 signature for API request.
        
        The signature is computed over the following string:
        METHOD + timestamp + path + query_string + body
        
        Args:
            method: HTTP method (GET, POST, PUT, DELETE)
            timestamp: Unix timestamp as string (seconds)
            path: API endpoint path (e.g., "/v2/orders")
            query_string: Query parameters (e.g., "?product_id=1&state=open" or "product_id=1&state=open")
            body: Request body as JSON string (empty string for GET requests)
            
        Returns:
            Hexadecimal signature string
            
        Example:
            >>> auth = DeltaAuth("key", "secret")
            >>> sig = auth.generate_signature(
            ...     method="POST",
            ...     timestamp="1542110948",
            ...     path="/v2/orders",
            ...     query_string="",
            ...     body='{"product_id":27,"side":"buy","size":10}'
            ... )
        """
        # Ensure query_string starts without '?' for signature generation
        if query_string.startswith("?"):
            query_string = query_string[1:]
        
        # If query_string is present, add '?' prefix for signature
        if query_string:
            query_string = "?" + query_string
        
        # Create signature data string
        signature_data = f"{method}{timestamp}{path}{query_string}{body}"
        
        # Convert strings to bytes
        message = signature_data.encode('utf-8')
        secret = self.api_secret.encode('utf-8')
        
        # Generate HMAC-SHA256 signature
        signature_hash = hmac.new(secret, message, hashlib.sha256)
        
        # Return hexadecimal representation
        return signature_hash.hexdigest()
    
    def generate_headers(
        self,
        method: str,
        path: str,
        query_string: str = "",
        body: str = "",
        timestamp: Optional[str] = None,
        user_agent: str = "delta-exchange-python-client/0.1.0"
    ) -> Dict[str, str]:
        """
        Generate all required headers for an authenticated API request.
        
        Args:
            method: HTTP method (GET, POST, PUT, DELETE)
            path: API endpoint path
            query_string: Query parameters (with or without leading '?')
            body: Request body as JSON string
            timestamp: Optional timestamp (generated automatically if not provided)
            user_agent: User agent string
            
        Returns:
            Dictionary of headers for the request
            
        Example:
            >>> auth = DeltaAuth("key", "secret")
            >>> headers = auth.generate_headers(
            ...     method="GET",
            ...     path="/v2/positions",
            ...     query_string="product_id=1"
            ... )
            >>> # Use headers in requests.get()
        """
        # Generate timestamp if not provided
        if timestamp is None:
            timestamp = str(int(time.time()))
        
        # Generate signature
        signature = self.generate_signature(
            method=method,
            timestamp=timestamp,
            path=path,
            query_string=query_string,
            body=body
        )
        
        # Return headers dictionary
        return {
            "api-key": self.api_key,
            "signature": signature,
            "timestamp": timestamp,
            "User-Agent": user_agent,
            "Content-Type": "application/json",
            "Accept": "application/json"
        }
    
    def generate_websocket_auth_payload(self, timestamp: Optional[str] = None) -> Dict:
        """
        Generate authentication payload for WebSocket connection.
        
        WebSocket authentication requires sending an auth message with:
        - api-key
        - signature (computed over "GET" + timestamp + "/live")
        - timestamp
        
        Args:
            timestamp: Optional timestamp (generated automatically if not provided)
            
        Returns:
            Dictionary containing the auth payload
            
        Example:
            >>> auth = DeltaAuth("key", "secret")
            >>> auth_payload = auth.generate_websocket_auth_payload()
            >>> # Send via WebSocket: {"type": "auth", "payload": auth_payload}
        """
        # Generate timestamp if not provided
        if timestamp is None:
            timestamp = str(int(time.time()))
        
        # WebSocket auth signature uses: GET + timestamp + /live
        method = "GET"
        path = "/live"
        signature = self.generate_signature(
            method=method,
            timestamp=timestamp,
            path=path,
            query_string="",
            body=""
        )
        
        return {
            "api-key": self.api_key,
            "signature": signature,
            "timestamp": timestamp
        }
    
    @staticmethod
    def validate_timestamp(timestamp: str, max_age_seconds: int = 5) -> bool:
        """
        Validate that a timestamp is recent enough.
        
        Delta Exchange requires signatures to be generated within 5 seconds
        of the request. This method validates that a timestamp is fresh.
        
        Args:
            timestamp: Unix timestamp as string
            max_age_seconds: Maximum age in seconds (default: 5)
            
        Returns:
            True if timestamp is valid, False otherwise
            
        Example:
            >>> DeltaAuth.validate_timestamp("1542110948")
            False  # Too old
        """
        try:
            ts = int(timestamp)
            current_time = int(time.time())
            age = current_time - ts
            return 0 <= age <= max_age_seconds
        except (ValueError, TypeError):
            return False

